### PR TITLE
[PB-403]: Added VHD drive logic

### PR DESCRIPTION
**Pull request by larry-internxt**
- Added vhd necessary functions as mount, unmount and eject

### CODE REVIEW

**Comment by JoanVicens** [comment]
I have run into some problems:
New-VHD was not recognized as the name of a cmdlet. After enabling Hyper-V and restarting it got recognized. (I had to check both to work)


After that I'm still getting this error: `Error creating VHD drive: Error: Command failed: New-VHD -Path .\Internxt.vhdx -Dynamic -SizeBytes 10GB |Mount-VHD -Passthru |Initialize-Disk -Passthru |
      New-Partition -DriveLetter I -UseMaximumSize |Format-Volume -FileSystem NTFS -Confirm:$false -Force
New-VHD : You do not have the required permission to complete this task. Contact the administrator of the
authorization policy for the computer '************'`

**Comment by larry-internxt** [comment]
> I have run into some problems: New-VHD was not recognized as the name of a cmdlet. After enabling Hyper-V and restarting it got recognized. (I had to check both to work) 
> 
> After that I'm still getting this error: `Error creating VHD drive: Error: Command failed: New-VHD -Path .\Internxt.vhdx -Dynamic -SizeBytes 10GB |Mount-VHD -Passthru |Initialize-Disk -Passthru | New-Partition -DriveLetter I -UseMaximumSize |Format-Volume -FileSystem NTFS -Confirm:$false -Force New-VHD : You do not have the required permission to complete this task. Contact the administrator of the authorization policy for the computer '************'`

working on the hyper-v problem, and the last error can be solved executing desktop as admin shell

**Comment by JoanVicens** [comment]
Running the app with PowerShell as admin did work 🙆🏼 . But I run into this 
imagen

Also, we will be able to execute the command without privileges once is installed? Do we have to ask for permision to make the changes?

**Review by sg-gs — APPROVED** [review]
LGTM. But it is the VHD issue solved @JoanVicens @larry-internxt ?

**Comment by JoanVicens** [comment]
@sg-gs I still running into the format drive window. Plus having to execute the app as an administrator. We can try to tackle that in a separate task if you want

**Pull request merged**
