### PR TITLE
[PB-71]: Feat/Add FR language

### PR DESCRIPTION
**Pull request by larry-internxt**
- Added french translation configuration and resources
- Fixed an english translation text
- Fixed bug where LanguagePicker was not showing the button to change Language

### CODE REVIEW

**Comment by JoanVicens** [comment]
those translations:
```
issues
├── actions
├── short-error-messages
├── error-messages
├── report-modal
```

are still in English, I guess we are waiting for them to be ready.

Also missing the key `settings.general.sync.change-folder`

**Comment by JoanVicens** [comment]
the `fr.json` has to be included in the i18n service

**Comment by JoanVicens** [comment]
The tabs on the list of issues need to be adjusted to accommodate the longer texts, they look like this rn:
![imatge](https://user-images.githubusercontent.com/38570230/231707276-094322f3-9e65-4be8-9ab3-1cff466ac085.

**Comment by larry-internxt** [comment]
> those translations:
> 
> ```
> issues
> ├── actions
> ├── short-error-messages
> ├── error-messages
> ├── report-modal
> ```
> 
> are still in English, I guess we are waiting for them to be ready.
> 
> Also missing the key `settings.general.sync.change-folder` (this was recently added on master-erb)

I see them in french 😅, and I also see the key 'settings.general.sync.change-folder' translated to french 🤔

**Comment by larry-internxt** [comment]
> the `fr.json` has to be included in the i18n service

I think this was included yesterday morning 🤔

**Review by JoanVicens — APPROVED** [review]

**Pull request merged**
