### PR TITLE
[PB-425]: (feature) Desktop new onboarding + configure backups

### PR DESCRIPTION
**Pull request by PixoDev**
- New desktop onboarding
- Allow to configure Backups from the onboarding

### CODE REVIEW

**Comment by JoanVicens** [comment]
The cancel button is not work for me image

**Comment by JoanVicens** [comment]
After selecting 2 folders if I go to the backups settings does not show that backups is active

**Comment by PixoDev** [comment]
> After selecting 2 folders if I go to the backups settings does not show that backups is active

Mm maybe I missed something I just created the folders and linked the deviceId, to them, the folders are created correctly and I can view them on the select folders option in preferences, I'll give it a check thx

**Comment by JoanVicens** [comment]
> > After selecting 2 folders if I go to the backups settings does not show that backups is active
> 
> Mm maybe I missed something I just created the folders and linked the deviceId, to them, the folders are created correctly and I can view them on the select folders option in preferences, I'll give it a check thx

I think you are only missing to set a flag on the Local Store.

**Comment by PixoDev** [comment]
> This looks a bit crammed (between "automatic backups in Settings" and "Internxt Drive is ready")and the check box icons don't have the same size image

Flex issue here, already fixed

**Comment by PixoDev** [comment]
> This looks a bit crammed (between "automatic backups in Settings" and "Internxt Drive is ready")and the check box icons don't have the same size image

Fixed this on the last commit

**Comment by PixoDev** [comment]
> > > After selecting 2 folders if I go to the backups settings does not show that backups is active
> > 
> > 
> > Mm maybe I missed something I just created the folders and linked the deviceId, to them, the folders are created correctly and I can view them on the select folders option in preferences, I'll give it a check thx
> 
> I think you are only missing to set a flag on the Local Store.

Fixed, added the config value so it gets checked

**Review by JoanVicens — APPROVED** [review]

**Pull request merged**
